/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.pucv.mavenproject1;
import entidades.ObraArte;
import entidades.Pintura;
import entidades.Escultura;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author dmena
 */
public class VentanaEditarObra extends javax.swing.JFrame {
    private ObraArte obraAEditar;
    private ArrayList<ObraArte> listaObras;
    /**
     * Creates new form VentanaEditarObra
     */
    public VentanaEditarObra() {
        initComponents();
    }
    
    public VentanaEditarObra(ObraArte obra, ArrayList<ObraArte> listaObras) {
        this.obraAEditar = obra;
        this.listaObras = listaObras;
        initComponents();
        cargarDatosObra();
        configurarBotones();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscultura = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtDimensiones3D = new javax.swing.JTextField();
        panelPintura = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEstilo = new javax.swing.JTextField();
        txtSoporte = new javax.swing.JTextField();
        txtDimensiones2D = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Material :");

        jLabel6.setText("Peso :");

        jLabel7.setText("Dimensiones :");

        txtMaterial.setText("jTextField5");

        txtPeso.setText("jTextField6");

        txtDimensiones3D.setText("jTextField7");

        javax.swing.GroupLayout panelEsculturaLayout = new javax.swing.GroupLayout(panelEscultura);
        panelEscultura.setLayout(panelEsculturaLayout);
        panelEsculturaLayout.setHorizontalGroup(
            panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsculturaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEsculturaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDimensiones3D))
                    .addGroup(panelEsculturaLayout.createSequentialGroup()
                        .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txtPeso))))
                .addContainerGap())
        );
        panelEsculturaLayout.setVerticalGroup(
            panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsculturaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDimensiones3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel8.setText("Estilo :");

        jLabel9.setText("Soporte :");

        jLabel10.setText("Dimesiones :");

        txtEstilo.setText("jTextField8");

        txtSoporte.setText("jTextField9");

        txtDimensiones2D.setText("jTextField10");

        javax.swing.GroupLayout panelPinturaLayout = new javax.swing.GroupLayout(panelPintura);
        panelPintura.setLayout(panelPinturaLayout);
        panelPinturaLayout.setHorizontalGroup(
            panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPinturaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(36, 36, 36)
                        .addComponent(txtEstilo))
                    .addGroup(panelPinturaLayout.createSequentialGroup()
                        .addGroup(panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoporte)
                            .addComponent(txtDimensiones2D, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelPinturaLayout.setVerticalGroup(
            panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinturaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDimensiones2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Nuevo ID :");

        jLabel2.setText("Nuevo Año :");

        jLabel3.setText("Nuevo Titulo :");

        jLabel4.setText("Nuevo Precio :");

        txtId.setText("jTextField1");

        txtAnio.setText("jTextField2");

        txtTitulo.setText("jTextField3");

        txtPrecio.setText("jTextField4");

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtAnio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addComponent(txtPrecio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelEscultura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(btnAceptar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panelPintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPintura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEscultura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void configurarBotones()
    {
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guardarCambios();
            }
        });
        
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dispose();
            }
        });
    }
    
    private void cargarDatosObra()
    {
        // Datos generales
        txtId.setText(String.valueOf(obraAEditar.getId()));
        txtTitulo.setText(obraAEditar.getTitulo());
        txtAnio.setText(String.valueOf(obraAEditar.getAnio()));
        txtPrecio.setText(String.valueOf(obraAEditar.getPrecio()));
        
        // Configurar tipo de obra y cargar datos específicos
        if (obraAEditar instanceof Pintura)
        {
            cargarDatosPintura((Pintura) obraAEditar);
            cambiarPanelTipoObra(true);
        }
        else if (obraAEditar instanceof Escultura)
        {
            cargarDatosEscultura((Escultura) obraAEditar);
            cambiarPanelTipoObra(false);
        }
        
    }
    
    private void cargarDatosPintura(Pintura pintura) {
        txtEstilo.setText(pintura.getEstilo());
        txtSoporte.setText(pintura.getSoporte());
        txtDimensiones2D.setText(pintura.getDimensiones2D());
    }
    
    private void cargarDatosEscultura(Escultura escultura) {
        txtMaterial.setText(escultura.getMaterial());
        txtPeso.setText(escultura.getPeso());
        txtDimensiones3D.setText(escultura.getDimensiones3D());
    }
    
    private void cambiarPanelTipoObra(boolean condicion)
    {
        if(condicion)
        {
           panelPintura.setVisible(true);
           panelEscultura.setVisible(false);
        }
        else
        {
           panelEscultura.setVisible(true);
           panelPintura.setVisible(false);
        }
        
    }
    
    private void guardarCambios()
    {
        try {
            // Validaciones básicas
            if (txtTitulo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El título es obligatorio");
                return;
            }
            
            if (txtId.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El ID es obligatorio");
                return;
            }
            
            if (txtAnio.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "El Año es obligatorio");
                return;
            }
            
            if (txtPrecio.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "El Precio es obligatorio");
                return;
            }
            int nuevoId = Integer.parseInt(txtId.getText().trim());
            
            // Verificar si el ID ya existe (en otras obras)
            for (ObraArte obra : listaObras) {
                if (obra != obraAEditar && obra.getId() == nuevoId) {
                    JOptionPane.showMessageDialog(this, "Ya existe otra obra con ese ID");
                    return;
                }
            }
            
            // Actualizar datos generales
            obraAEditar.setId(nuevoId);
            obraAEditar.setTitulo(txtTitulo.getText().trim());
            obraAEditar.setAnio(Integer.parseInt(txtAnio.getText().trim()));
            obraAEditar.setPrecio(Float.parseFloat(txtPrecio.getText().trim()));
            
            // Actualizar datos específicos según el tipo
            if (obraAEditar instanceof Pintura)
            {
                Pintura pintura = (Pintura) obraAEditar;
                pintura.setEstilo(txtEstilo.getText().trim());
                pintura.setSoporte(txtSoporte.getText().trim());
                pintura.setDimensiones2D(txtDimensiones2D.getText().trim());
            }
            else if (obraAEditar instanceof Escultura)
            {
                Escultura escultura = (Escultura) obraAEditar;
                escultura.setMaterial(txtMaterial.getText().trim());
                escultura.setPeso(txtPeso.getText().trim());
                escultura.setDimensiones3D(txtDimensiones3D.getText().trim());
            }
            
            JOptionPane.showMessageDialog(this, "Obra actualizada exitosamente");
            dispose();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en formatos numéricos: verifique ID, año y precio");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEditarObra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelEscultura;
    private javax.swing.JPanel panelPintura;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDimensiones2D;
    private javax.swing.JTextField txtDimensiones3D;
    private javax.swing.JTextField txtEstilo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSoporte;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
